### ISSUE TITLE
Field hardware

### ISSUE THREAD

**Issue by stakach** [DVM000/smart_camera_trap_research#1]
Hi,

I was reading your journal article: https://www.sciencedirect.com/science/article/pii/S1574954124003571
and I'm interested in the bill of materials for your field hardware, cases, batteries used etc - if you are willing to share?

I've been building a conceptually similar system on the same hardware (Pi Zero 2W) and am at the stage of testing in the field.
https://github.com/spider-gazelle/edge-ai

We're doing an efficacy study for an AI spray or non-lethal trap system for invasive species in Australia.
We'll definitively be referencing your paper in any articles that come from our work

If interested I can share our current hardware stack, it's somewhat similar to this:
https://vontaka.ch/chicken_door/
I built that to test GPIO and power management systems

**Comment by DVM000** [comment]
Hi Stephen,
For the key components, we used the following: 1) a Raspberry Pi Zero 2W, 2) a Panasonic PIR sensor (model EKMB1303111K) https://docs.rs-online.com/0956/0900766b815fdfa5.pdf, 3) a Raspberry Pi Camera Module V2, 4) a USB battery, and 5) an LED. 

We connected the PIR sensor to GPIO17, Ground and DC power pins of the Raspberry Pi accordingly (GPIO17 is used for OUT pin of PIR, and can be adjusted in the configuration.ini file under the INPUT_PIN parameter). The LED was connected to GPIO4, which is also configurable (OUTPUT_PIN), and to Ground -- the LED is optional and it indicates whether the camera is capturing images or not. The Raspberry Pi camera was attached via the CSI interface. To house all the components (RPi, sensor, camera, and LED), a custom 3D-printed case can be created.

I hope this is helpful. Looking forward to your feedback!

**Comment by DVM000** [comment]
More documentation about this and camera operation have been added in the ./doc folder.

@stakach, in addition, to study the camera operation in your own case study, you can change the animal crops in ./data/cat_crops to add crops of the species you expect to capture in the images.
